gloryautotech/GFL_FE_V1

src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts

on-enter focus in planning slip

on-enter focus in planning slip

---

src/app/@theme/model/admin.ts
src/app/@theme/services/admin.service.ts
src/app/pages/admin/admin.component.html
src/app/pages/admin/admin.component.ts
src/app/pages/batch-shuffle/shuffle/shuffle.component.html
src/app/pages/finished-meter/add-edit-finished-meter/add-edit-finished-meter.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/party/add-edit-party/add-edit-party.component.ts
src/app/pages/payment/advance-payment/advance-payment.component.html
src/app/pages/payment/bill-payment/bill-payment.component.html
src/app/pages/process/add-function/add-function.component.ts
src/app/pages/program/add-edit-program/add-edit-program.component.html
src/app/pages/quality/add-edit-quality/add-edit-quality.component.html
src/app/pages/quality/add-edit-quality/add-edit-quality.component.ts
src/app/pages/shade/add-edit-shade/add-edit-shade.component.html
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.html

party name - party code in dropdown - machine-machine category add - show

Machine bind

---

src/app/pages/addition-slip/addition-slip.component.ts
src/app/pages/jet-planning/jet-planning.component.ts
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts

Validation print slip

---

src/app/@theme/interceptor/httpInterceptor.ts
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts

Validation generate slip & HTTP Interceptor

Validation generate slip

---

src/app/pages/dyeing-process/add-dyeing-process-step/add-dyeing-process-step.component.html
src/app/pages/dyeing-process/add-dyeing-process-step/add-dyeing-process-step.component.ts
src/app/pages/dyeing-process/add-edit-dyeing-process/add-edit-dyeing-process.component.ts
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts

Dyeing process issue chemical list and delete step

Dyeing process issue

---

src/app/@theme/interceptor/httpInterceptor.ts
src/app/@theme/model/shade.ts
src/app/pages/pages.component.ts
src/app/pages/quality/add-edit-quality/add-edit-quality.component.ts
src/app/pages/shade/add-edit-shade/add-edit-shade.component.ts
src/app/pages/stock-batch/stock-batch.component.ts
src/app/pages/user/add-edit-user/add-edit-user.component.html
src/app/pages/user/add-edit-user/add-edit-user.component.ts

shade - user drop down- login fix

Total wt mt

---

src/app/@theme/styles/styles.scss
src/app/pages/admin/admin.component.html
src/app/pages/batch-shuffle/shuffle/shuffle.component.html
src/app/pages/color/add-edit-color/add-edit-color.component.html
src/app/pages/color/issue-color-box/issue-color-box.component.html
src/app/pages/dyeing-process/add-edit-dyeing-process/add-edit-dyeing-process.component.html
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.html
src/app/pages/jet-planning/jet-planning.component.html
src/app/pages/party/add-edit-party/add-edit-party.component.html
src/app/pages/payment/advance-payment/advance-payment.component.html
src/app/pages/payment/bill-payment/bill-payment.component.html
src/app/pages/program/add-edit-program/add-edit-program.component.html
src/app/pages/quality/add-edit-quality/add-edit-quality.component.html
src/app/pages/shade/add-edit-shade/add-edit-shade.component.html
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.html
src/app/pages/supplier/add-edit-supplier/add-edit-supplier.component.html
src/app/pages/user/add-edit-user/add-edit-user.component.html
src/app/pages/water-jet/add-edit-water-jet/add-edit-water-jet.component.html

input-required class add in all the file

Required create class

---

src/app/pages/finished-meter/add-edit-finished-meter/add-edit-finished-meter.component.ts
src/app/pages/payment/bill-payment/bill-payment.component.html
src/app/pages/payment/bill-payment/bill-payment.component.ts

bill payment issue and all batch in finished meter

Payment issue

---

src/app/@theme/components/export-popup/export-popup.component.html
src/app/@theme/styles/styles.scss
src/app/pages/party/party.component.html
src/app/pages/shade/add-edit-shade/add-edit-shade.component.html

Party module class changes

---

src/app/pages/party/add-edit-party/add-edit-party.component.html
src/app/pages/party/party.component.html
src/app/pages/quality/add-edit-quality/add-edit-quality.component.html
src/app/pages/quality/quality.component.html

qality module class add

---

src/app/pages/production-planning/shade-with-batch/shade-with-batch.component.ts
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts

Jet weight fix

---

src/app/pages/generate-invoice/print-Layout/print-layout.component.html
src/app/pages/generate-invoice/print-Layout/print-layout.component.scss
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/production-planning/add-shade/add-shade.component.html

Jet number ellipsis remove and generate invoice changes

Jet number ellipsis remove

---

src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts
src/app/pages/shade/add-edit-shade/add-edit-shade.component.ts

add-edit-shade rounding upto 2 decimal
planning-slip component on enter issue resolved

Gfl tickets

---

src/app/pages/generate-invoice/print-Layout/print-layout.component.html
src/app/pages/generate-invoice/print-Layout/print-layout.component.scss

Print d data

---

src/app/@theme/pipes/showOnlyChemicalList.pipe.ts
src/app/@theme/services/dyeing-process.service.ts
src/app/@theme/services/party.service.ts
src/app/@theme/services/quality.service.ts
src/app/@theme/theme.module.ts
src/app/pages/addition-slip/addition-slip.component.html
src/app/pages/color/add-edit-color/add-edit-color.component.ts
src/app/pages/dyeing-process/add-dyeing-process-step/add-dyeing-process-step.component.html
src/app/pages/dyeing-process/add-edit-dyeing-process/add-edit-dyeing-process.component.html
src/app/pages/dyeing-process/add-edit-dyeing-process/add-edit-dyeing-process.component.ts
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts
src/app/pages/party/add-edit-party/add-edit-party.component.html
src/app/pages/party/add-edit-party/add-edit-party.component.ts
src/app/pages/production-planning/production-planning.component.ts
src/app/pages/quality/add-edit-quality/add-edit-quality.component.html
src/app/pages/quality/add-edit-quality/add-edit-quality.component.ts
src/app/pages/shade/pending-apc/pending-apc.component.ts
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.html
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts
src/app/pages/user/add-edit-user/add-edit-user.component.html
src/app/pages/user/add-edit-user/add-edit-user.component.ts

Trello all tickets issues

---

src/app/@theme/styles/styles.scss
src/app/pages/generate-invoice/invoice-report/invoice-report.component.html
src/app/pages/generate-invoice/print-Layout/print-layout.component.html
src/app/pages/generate-invoice/print-Layout/print-layout.component.scss
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.scss
src/app/pages/production-planning/add-shade/add-shade.component.html

New file inline css remove

---

src/app/@theme/model/printInvoice.ts
src/app/pages/generate-invoice/print-Layout/print-layout.component.html
src/app/pages/generate-invoice/print-Layout/print-layout.component.ts

Invoice lot table design

---

src/app/@theme/styles/styles.scss
src/app/pages/miscellaneous/miscellaneous.module.ts
src/app/pages/miscellaneous/not-found/not-found.component.html
src/app/pages/miscellaneous/not-found/not-found.component.ts

New report UI page

---

src/app/pages/admin/admin.component.html
src/app/pages/admin/admin.component.ts
src/app/pages/dyeing-process/add-edit-dyeing-process/add-edit-dyeing-process.component.html

Test changes

---

src/app/pages/dyeing-process/add-edit-dyeing-process/add-edit-dyeing-process.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.scss
src/app/pages/shade/add-edit-shade/add-edit-shade.component.html
src/app/pages/shade/add-edit-shade/add-edit-shade.component.ts

Slip color, shade amount issue

Slip color, shade amount issue

---

src/app/@theme/model/user.ts
src/app/@theme/pipes/designation.pipe.ts
src/app/pages/admin/admin.component.html
src/app/pages/user/add-edit-user/add-edit-user.component.html
src/app/pages/user/add-edit-user/add-edit-user.component.ts

user designation fix

---

src/app/@theme/styles/styles.scss

Task mb design

---

src/app/@theme/styles/styles.scss
src/app/pages/production-planning/production-planning.component.html

progress changes

---

src/app/@theme/guards/admin.guard.ts
src/app/@theme/guards/attendance.guard.ts
src/app/@theme/guards/color.guard.ts
src/app/@theme/guards/dyeing-process.guard.ts
src/app/@theme/guards/dyeing-slip.guard.ts
src/app/@theme/guards/employee-registration.guard.ts
src/app/@theme/guards/finished-meter.guard.ts
src/app/@theme/guards/input-data.guard.ts
src/app/@theme/guards/invoice.guard.ts
src/app/@theme/guards/jet-planning.guard.ts
src/app/@theme/guards/merge-batch.guard.ts
src/app/@theme/guards/party.guard.ts
src/app/@theme/guards/payment.guard.ts
src/app/@theme/guards/process.guard.ts
src/app/@theme/guards/production-planning.guard.ts
src/app/@theme/guards/program.guard.ts
src/app/@theme/guards/purchase.guard.ts
src/app/@theme/guards/quality.guard.ts
src/app/@theme/guards/report.guard.ts
src/app/@theme/guards/shade.guard.ts
src/app/@theme/guards/stock-batch.guard.ts
src/app/@theme/guards/supplier-rate.guard.ts
src/app/@theme/guards/supplier.guard.ts
src/app/@theme/guards/task.guard.ts
src/app/@theme/guards/user.guard.ts
src/app/@theme/guards/water-jet.guard.ts
src/app/pages/user/add-edit-user/add-edit-user.component.html
src/app/pages/user/add-edit-user/add-edit-user.component.ts

permissions issue

---

src/app/@theme/styles/styles.scss
src/app/pages/task/task.component.html

Task mobile btn create

---

src/app/@theme/services/task.service.ts
src/app/pages/task/add-edit-task/add-edit-task.component.ts
src/app/pages/task/task.component.html
src/app/pages/task/task.component.ts

Task dashboard api

---

src/app/pages/admin/admin.component.html
src/app/pages/admin/admin.component.ts
src/app/pages/user/add-edit-user/add-edit-user.component.html
src/app/pages/user/add-edit-user/add-edit-user.component.ts

admin purchase delete edit fix

admin purchase delete edit fix

---

src/app/@theme/styles/styles.scss
src/app/pages/purchase/add-edit-purchase/add-edit-purchase.component.html
src/app/pages/registration/add-edit-registration/add-edit-registration.component.html

Preview design changes

---

src/app/@theme/styles/styles.scss
src/app/pages/task/add-edit-task/add-edit-task.component.html
src/app/pages/task/task.component.html

Changes task module trello

---

src/app/pages/generate-invoice/generate-invoice.component.html
src/app/pages/generate-invoice/generate-invoice.component.ts
src/app/pages/stock-batch/stock-batch.component.html
src/app/pages/stock-batch/stock-batch.component.ts

print button in all row stock and invoice

print button in all row stock and invoice

---

src/app/@theme/services/admin.service.ts
src/app/@theme/services/common.service.ts
src/app/@theme/services/stock-batch.service.ts
src/app/pages/admin/admin.component.ts
src/app/pages/batch-shuffle/shuffle/shuffle.component.ts
src/app/pages/merge-batch/merge-batch/merge-batch.component.ts
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts

batch sequence update

---

src/app/@theme/model/admin.ts
src/app/@theme/services/admin.service.ts
src/app/pages/admin/admin.component.html
src/app/pages/admin/admin.component.ts
src/app/pages/task/task-detail/task-detail.component.html
src/app/pages/task/task.component.html
src/app/pages/task/task.component.ts

authorization in admin
task priority
on tab click api call

Task priority

---

src/app/pages/color/add-edit-color/add-edit-color.component.ts
src/app/pages/finished-meter/add-edit-finished-meter/add-edit-finished-meter.component.ts
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.html
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.ts
src/app/pages/production-planning/production-planning.component.ts

changes in color, production, finish meter, invoice

Testing changes

---

src/app/@theme/model/registration.ts
src/app/pages/attendance/attendance.component.ts
src/app/pages/attendance/scan-qr/scan-qr.component.html
src/app/pages/attendance/scan-qr/scan-qr.component.ts
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts
src/app/pages/registration/add-edit-registration/add-edit-registration.component.html
src/app/pages/registration/add-edit-registration/add-edit-registration.component.ts
src/app/pages/stock-batch/job-card/job-card.component.html

changes in job card , jet planning attendance register

103 changes

---

src/app/pages/batch-shuffle/shuffle/shuffle.component.ts
src/app/pages/merge-batch/view-merge-batch/view-merge-batch.component.ts

batch-party-fix

---

src/app/pages/generate-report/generate-report.component.ts
src/app/pages/party/party.component.ts

party-view-all distingush batchlist in report

party-view-all distingush batchhlist in report

---

src/app/pages/attendance/attendance.component.html
src/app/pages/attendance/attendance.component.ts
src/app/pages/attendance/scan-qr/scan-qr.component.html
src/app/pages/attendance/scan-qr/scan-qr.component.ts
src/app/pages/generate-report/generate-report.component.html
src/app/pages/generate-report/generate-report.component.ts
src/app/pages/merge-batch/merge-batch/merge-batch.component.html
src/app/pages/merge-batch/view-merge-batch/view-merge-batch.component.html

Attendance date fix , merge batch, report

Batch party fix

---

src/app/pages/color/color.component.ts
src/app/pages/party/party.component.ts
src/app/pages/quality/quality.component.ts
src/app/pages/shade/shade.component.ts
src/app/pages/stock-batch/stock-batch.component.ts
src/app/pages/supplier/supplier.component.ts

permission view all own group

---

src/app/@theme/services/registration.service.ts
src/app/@theme/styles/styles.scss
src/app/app.module.ts
src/app/pages/attendance/attendance.component.ts
src/app/pages/attendance/scan-qr/scan-qr.component.html
src/app/pages/color/add-edit-color/add-edit-color.component.html
src/app/pages/color/add-edit-color/add-edit-color.component.ts
src/app/pages/dyeing-process/add-dyeing-process-step/add-dyeing-process-step.component.html
src/app/pages/dyeing-process/add-dyeing-process-step/add-dyeing-process-step.component.ts
src/app/pages/merge-batch/merge-batch/merge-batch.component.html
src/app/pages/merge-batch/merge-batch/merge-batch.component.ts
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.html
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts

merge batch dying process date

merge batch dying process date

---

src/app/pages/attendance/scan-qr/scan-qr.component.html
src/app/pages/attendance/scan-qr/scan-qr.component.ts
src/manifest.webmanifest

permission

---

src/app/@theme/interceptor/httpInterceptor.ts

Camera permission

---

src/app/pages/generate-invoice/print-Layout/print-layout.component.html
src/app/pages/jet-planning/planning-slip/planning-slip.component.html
src/app/pages/pages-menu.ts

invoice change other slip round

invoice change other slip round

---

src/app/@theme/services/common.service.ts
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.ts
src/app/pages/generate-invoice/print-Layout/print-layout.component.ts
src/app/pages/party/add-edit-party/add-edit-party.component.html
src/app/pages/party/add-edit-party/add-edit-party.component.ts

Small changess

---

src/app/pages/production-planning/production-planning.component.ts

production planning issue

---

src/app/@theme/model/dyeing-process.ts
src/app/pages/dyeing-process/add-dyeing-process-step/add-dyeing-process-step.component.html
src/app/pages/dyeing-process/add-dyeing-process-step/add-dyeing-process-step.component.ts
src/app/pages/dyeing-process/add-edit-dyeing-process/add-edit-dyeing-process.component.html
src/app/pages/dyeing-process/dyeing-process.component.scss

format item dropdown
add shade type
add acid wash

dyeing process changes

---

src/app/@theme/services/jet-planning.service.ts
src/app/pages/color/issue-color-box/issue-color-box.module.ts
src/app/pages/e-commerce/e-commerce.module.ts
src/app/pages/input-data/input-data.module.ts
src/app/pages/jet-planning/jet-planning-routing.module.ts
src/app/pages/production-planning/production-planning.component.html
src/app/pages/production-planning/production-planning.component.ts
src/app/pages/program/program.module.ts

jet start option

---

src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts

stockbatch enter issue

---

src/app/@theme/services/quality.service.ts
src/app/pages/quality/add-edit-quality/add-edit-quality.component.html
src/app/pages/quality/add-edit-quality/add-edit-quality.component.ts

quality id unique party wise

---

src/app/pages/generate-invoice/print-Layout/print-layout.component.html
src/app/pages/generate-invoice/print-Layout/print-layout.component.ts
src/app/pages/quality/add-edit-quality/add-edit-quality.component.html
src/app/pages/quality/add-edit-quality/add-edit-quality.component.ts

quality invoice changes

---

src/app/pages/generate-invoice/print-Layout/print-layout.component.ts

invoice quality 4 rows

---

src/app/pages/production-planning/add-shade/add-shade.component.html
src/app/pages/production-planning/production-planning.component.html
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.html
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.scss
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts

stock batch totals

---

src/app/@theme/services/dyeing-process.service.ts
src/app/@theme/styles/styles.scss
src/app/pages/addition-slip/addition-slip-routing.module.ts
src/app/pages/addition-slip/addition-slip.module.ts
src/app/pages/addition-slip/dyeing-slip/dyeing-slip.component.html
src/app/pages/addition-slip/dyeing-slip/dyeing-slip.component.spec.ts
src/app/pages/addition-slip/dyeing-slip/dyeing-slip.component.ts
src/app/pages/pages-menu.ts
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.html
src/app/pages/supplier/add-edit-supplier-rate/add-edit-supplier-rate.component.html
src/app/pages/supplier/add-edit-supplier-rate/add-edit-supplier-rate.component.ts

data table for dyeing slip and supplier export

Data table

---

src/app/@theme/components/export-popup/export-popup.component.ts

export Pop up

---

src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.html
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.ts
src/app/pages/generate-invoice/invoice-report/invoice-report.component.html
src/app/pages/generate-invoice/invoice-report/invoice-report.component.scss
src/app/pages/generate-invoice/invoice-report/invoice-report.component.ts

invoice report change

---

src/app/@theme/services/stock-batch.service.ts
src/app/pages/generate-invoice/invoice-report/invoice-report.component.ts
src/app/pages/shade/add-edit-shade/add-edit-shade.component.ts
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.html
src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts
src/app/pages/stock-batch/lot-return-view/lot-return-view.component.html
src/app/pages/stock-batch/lot-return-view/lot-return-view.component.spec.ts
src/app/pages/stock-batch/lot-return-view/lot-return-view.component.ts
src/app/pages/stock-batch/lot-return/lot-return.component.html
src/app/pages/stock-batch/lot-return/lot-return.component.scss
src/app/pages/stock-batch/lot-return/lot-return.component.spec.ts
src/app/pages/stock-batch/lot-return/lot-return.component.ts
src/app/pages/stock-batch/print-lot-return/print-lot-return.component.html
src/app/pages/stock-batch/print-lot-return/print-lot-return.component.scss
src/app/pages/stock-batch/print-lot-return/print-lot-return.component.ts
src/app/pages/stock-batch/stock-batch-routing.module.ts
src/app/pages/stock-batch/stock-batch.module.ts

Lot return print

---

src/app/pages/stock-batch/add-edit-stock-batch/add-edit-stock-batch.component.ts

stock in - wtPer100Mtr fix

---

src/app/@theme/layouts/one-column/one-column.layout.ts
src/app/@theme/services/generate-invoice.service.ts
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.html
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.ts
src/app/pages/generate-invoice/generate-invoice-routing.module.ts
src/app/pages/generate-invoice/generate-invoice.module.ts
src/app/pages/generate-invoice/received-invoice/received-invoice.component.html
src/app/pages/generate-invoice/received-invoice/received-invoice.component.spec.ts
src/app/pages/generate-invoice/received-invoice/received-invoice.component.ts
src/app/pages/generate-invoice/sign-invoice/sign-invoice.component.html
src/app/pages/generate-invoice/sign-invoice/sign-invoice.component.spec.ts
src/app/pages/generate-invoice/sign-invoice/sign-invoice.component.ts
src/app/pages/jet-planning/planning-slip/planning-slip.component.ts
src/app/pages/stock-batch/lot-return-view/lot-return-view.component.html
src/app/pages/stock-batch/lot-return/lot-return.component.html
src/app/pages/stock-batch/lot-return/lot-return.component.ts
src/app/pages/stock-batch/print-lot-return/print-lot-return.component.html

custom party lot return
print slip issue
navigation issue
signed invoice crud

Lot return custom

---

src/app/@theme/model/printInvoice.ts
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.html
src/app/pages/generate-invoice/add-edit-invoice/add-edit-invoice.component.ts
src/app/pages/generate-invoice/print-Layout/print-layout.component.html
src/app/pages/generate-invoice/print-Layout/print-layout.component.ts

invoice changes

---

src/app/@theme/services/common.service.ts
src/app/@theme/services/production-planning.service.ts
src/app/pages/production-planning/add-shade/add-shade.component.html
src/app/pages/production-planning/add-shade/add-shade.component.ts

Factory Shade no
